FROM ubuntu

#COPY app.txt /app.txt
#COPY ./ /

#ENTRYPOINT ["/bin/bash", "-c","sleep 500"]

RUN apt update && apt install -y git

ENTRYPOINT ["/bin/bash","-c","sleep 500"]
#ENTRYPOINT ["/bin/bash", "-c", "echo hello"]